name: ridesync
description: RideSync mobile app
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.5.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.4.4
  firebase_database: ^11.0.0
  firebase_storage: ^12.0.0
  google_maps_flutter: ^2.7.0
  spotify_sdk: ^2.3.1
  url_launcher: ^6.3.0
  flutter_webrtc: ^0.9.45
  riverpod: ^2.5.1
  flutter_local_notifications: ^17.2.1
  http: ^1.2.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
